export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const GET_COUNTRIES_ID = 'GET_COUNTRIES_ID';
export const GET_COUNTRIES_NAME = 'GET_COUNTRIES_NAME';
export const POST_ACTIVITY = "POST_ACTIVITY";


